# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' read out of bound
#' 
#' @param sizeofarray gives size of array 
#' @return index of array out of bound
rcpp_read_out_of_bound <- function(sizeofarray) {
    .Call(`_testUBSAN_rcpp_read_out_of_bound`, sizeofarray)
}

#' use after deallocate
#' 
#' @param size of array 
#' @return index of array after deleting it
rcpp_use_after_deallocate <- function(size) {
    .Call(`_testUBSAN_rcpp_use_after_deallocate`, size)
}

#' use after free 
#' 
#' @param size_free free size of the array 
#' @return index of array after freeing it
rcpp_use_after_free <- function(size_free) {
    .Call(`_testUBSAN_rcpp_use_after_free`, size_free)
}

#' write index outofbound
#' 
#' @param boundvalue value stored in index 
#' @return stack_array index greater than size
rcpp_write_index_outofbound <- function(boundvalue) {
    .Call(`_testUBSAN_rcpp_write_index_outofbound`, boundvalue)
}

#' zero sized array
#' 
#' @param vectorvalue value at index zero
#' @return ptr value at zero index
rcpp_zero_sized_array <- function(vectorvalue) {
    .Call(`_testUBSAN_rcpp_zero_sized_array`, vectorvalue)
}

